### Global costmap parameters - load with the namespace "global_costmap" in the launch file ###

# The global frame for the global costmap to operate in.
global_frame: map

# The name of the frame for the base link of the robot.
robot_base_frame: base_link

# static_map: true

rolling_window: true
