global_frame: odom
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
width: 3.0
height: 3.0
resolution: 0.01
static_map: false
rolling_window: true
cost_scaling_factor: 0.5
inflation_radius: 0.1
