### Common costmap parameters ###

# footprint: [
#     [-0.500663781, -0.186784927],
#     [-0.0842645, -0.186784927],
#     [-0.0842645, -0.250748756],
#     [0.1342645, -0.250748756],
#     [0.1342645, -0.153217622],
#     [0.1960908, -0.153217622],
#     [0.1960908, 0.153217622],
#     [0.1342645, 0.153217622],
#     [0.1342645, 0.250748756],
#     [-0.0842645, 0.250748756],
#     [-0.0842645, 0.186784927],
#     [-0.500663781, 0.186784927]
# ]
robot_radius: 0.144

# Specifies the delay in transform (tf) data that is tolerable in seconds.
# This parameter serves as a safeguard to losing a link in the tf tree while
# still allowing an amount of latency the user is comfortable with to exist
# in the system.
transform_tolerance: 0.5  # 0.2

# The frequency in Hz for the map to be updated.
update_frequency: 2.0

# The frequency in Hz for the map to be publish display information.
publish_frequency: 1.0

# Whether or not to use a rolling window version of the costmap. If the
# static_map parameter is set to true, this parameter must be set to false.
rolling_window: false

# If true the full costmap is published to "~<name>/costmap" every update.
# If false only the part of the costmap that has changed is published on the
# "~<name>/costmap_updates" topic.
always_send_full_costmap: false

# static namespace. Defined in global and local costmap "plugins" dictionaries
static:
    map_topic: /map
    subscribe_to_updates: true


# inflation namespace. Defined in global and local costmap "plugins" dictionaries
inflation:
    enabled:              true
    cost_scaling_factor:  2.58
    inflation_radius:     0.1


# namespace named in dictionary above
obstacles:
    observation_sources: base_scan
    base_scan:
        topic: /rplidar/scan
        sensor_frame: laser
        # observation_persistence: 0.0
        # expected_update_rate: 0.0
        data_type: LaserScan
        clearing: true
        marking: true
        # max_obstacle_height: 2.0
        # min_obstacle_height: 0.0
        # obstacle_range: 2.5
        # raytrace_range: 3.0
        # inf_is_valid: false

# The maximum height of any obstacle to be inserted into the costmap in meters.
# This parameter should be set to be slightly higher than the height of your robot.
max_obstacle_height: 2.0

# The default maximum distance from the robot at which an obstacle will be
# inserted into the cost map in meters. This can be over-ridden on a per-sensor basis.
obstacle_range: 2.5

# The default range in meters at which to raytrace out obstacles from the map
# using sensor data. This can be over-ridden on a per-sensor basis.
raytrace_range: 3.0
