### Trajectory Planner parameters ###
# load with the namespace "TrajectoryPlannerROS" in the launch file

max_vel_x: 0.36
min_vel_x: 0.04
max_vel_y: 0.0
min_vel_y: 0.0
max_vel_theta: 3.0
min_in_place_vel_theta: 0.7
escape_vel: -0.2

acc_lim_theta: 100.0
acc_lim_x: 100.0
acc_lim_y: 0.0

holonomic_robot: true
