
use_map_topic: false
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

odom_model_type: diff-corrected

initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0

gui_publish_rate: 10.0
laser_max_beams: 720
laser_max_range: 8.0
min_particles: 500
max_particles: 10000

# kld_err: 0.05
# kld_z: 0.99
# odom_alpha1: 0.05
# odom_alpha2: 0.005

# translation std dev, m
# odom_alpha3: 0.010
# odom_alpha4: 0.05
# laser_z_hit: 0.95
# laser_z_short: 0.1
# laser_z_max: 0.05
# laser_z_rand: 0.05
# laser_sigma_hit: 0.2
# laser_lambda_short: 0.1
# laser_model_type: likelihood_field
# laser_model_type: beam
# laser_likelihood_max_dist: 2.0

# update_min_d: 0.05
# update_min_a: 0.02
# resample_interval: 2

# Increase tolerance because the computer can get quite busy
# transform_tolerance: 0.1
# recovery_alpha_slow: 0.01
# recovery_alpha_fast: 0.15
