boot_sound: "~/Music/sound_effects/bloop.wav"
shutdown_sound: "~/Music/sound_effects/ba ding.wav"
wifi_connect_sound: "~/Music/sound_effects/got thing.wav"
wifi_disconnect_sound: "~/Music/sound_effects/electric thud.wav"
volume: 20
